// created changepassword. It will update the users password in the database //Ibtissam 2013-12-30

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pysj
 */
public class ChangePassword extends javax.swing.JFrame {

    String sellerId;
    public ChangePassword(String sellerId) {
        initComponents();
        this.sellerId = sellerId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationLabel = new javax.swing.JLabel();
        labelCurrent = new javax.swing.JLabel();
        labelNew = new javax.swing.JLabel();
        labelNewRep = new javax.swing.JLabel();
        passwordOld = new javax.swing.JPasswordField();
        passwordNew = new javax.swing.JPasswordField();
        passwordNewRep = new javax.swing.JPasswordField();
        buttonCancel = new javax.swing.JButton();
        buttonChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        registrationLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        registrationLabel.setText("CHANGE PASSWORD");
        registrationLabel.setToolTipText("");

        labelCurrent.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        labelCurrent.setText("Current password");

        labelNew.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        labelNew.setText("New password");

        labelNewRep.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        labelNewRep.setText("Confirm new password");

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonChange.setText("Change");
        buttonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNewRep, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonChange)
                            .addGap(18, 18, 18)
                            .addComponent(buttonCancel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passwordNewRep, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(passwordOld)
                                .addComponent(passwordNew)))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registrationLabel)
                                .addGap(30, 30, 30)
                                .addComponent(labelCurrent))
                            .addComponent(passwordOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNew))
                    .addComponent(passwordNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNewRep)
                    .addComponent(passwordNewRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonChange))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
      dispose(); 
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeActionPerformed
        String dboldpass = "";
        String oldpassword = passwordOld.getText();
        String new1 = passwordNew.getText();
        String new2 = passwordNewRep.getText();
        try {
            Connection connection = null;
            ResultSet rset;
            try {
                connection = DriverManager.getConnection(MainClass.dbconnection, MainClass.user, MainClass.pass);
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
            Statement statement = null;
            try {
                statement = connection.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
            String query = "SELECT password FROM sellers WHERE sellerID = "  + "'" + sellerId + "'";
            rset = statement.executeQuery(query);
            while(rset.next()){
                dboldpass = rset.getString("password");
                
            }} catch (SQLException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(dboldpass.equals(oldpassword)) { 
            if (new1.equals(new2)) {try {
                 Connection connection = DriverManager.getConnection(MainClass.dbconnection, MainClass.user, MainClass.pass);
                 Statement statement = connection.createStatement();
                 String query = "UPDATE sellers SET password=? WHERE sellerID = " + "'" + sellerId + "'";
                 java.sql.PreparedStatement pst=connection.prepareStatement(query);
                 pst.setString(1, new1);
                 pst.execute();
                 JOptionPane.showMessageDialog(null, "Password is changed!", "Message", JOptionPane.PLAIN_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
                }
 } else { JOptionPane.showMessageDialog(null, "New password doesnt match!", "Error", JOptionPane.PLAIN_MESSAGE); } 
        } else { JOptionPane.showMessageDialog(null, "Old password is incorrect!", "Error", JOptionPane.PLAIN_MESSAGE); }
        dispose();
    }//GEN-LAST:event_buttonChangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonChange;
    private javax.swing.JLabel labelCurrent;
    private javax.swing.JLabel labelNew;
    private javax.swing.JLabel labelNewRep;
    private javax.swing.JPasswordField passwordNew;
    private javax.swing.JPasswordField passwordNewRep;
    private javax.swing.JPasswordField passwordOld;
    private javax.swing.JLabel registrationLabel;
    // End of variables declaration//GEN-END:variables
}
